{% set name = "conda-forge-feedstock-check-solvable" %}
{% set version = "0.12.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-feedstock-check-solvable/archive/refs/tags/{{ version }}.tar.gz
  sha256: aac56a82700b63167f649b3f265a255926a1aba3905514d6fb4edce79af62b77

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=7
    - setuptools >=45
  run:
    - python >={{ python_min }}
    - python-rapidjson
    - requests
    - ruamel.yaml
    - conda
    - conda-package-handling
    - conda-smithy
    - conda-build
    - ruamel.yaml.jinja2
    - conda-forge-metadata >=0.11.0
    - wurlitzer
    - psutil
    - zstandard
    - boltons >=23.0.0
    - py-rattler >=0.21.0,<0.22a0
    - pixi

test:
  requires:
    - python {{ python_min }}
  imports:
    - conda_forge_feedstock_check_solvable

about:
  home: https://github.com/regro/conda-forge-feedstock-check-solvable
  summary: A mamba-based package to check if a conda-forge feedstock is solvable.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - xhochy
